server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /health {
        proxy_pass http://backend:8234;
    }

    location /models {
        proxy_pass http://backend:8234;
    }

    location /metrics {
        proxy_pass http://backend:8234;
    }

    location /api/ {
        proxy_pass http://backend:8234;
    }

    location /v1/ {
        proxy_pass http://backend:8234;
    }
}
